version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 13000:3000
    depends_on:
      - db

  db:
    image: postgres:16beta1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: express_pzn
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
       