POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "akun": {
    "username": "pablo221233",
    "password": "rahasiaqwe",
    "id_role": 2001
  },
  "customer": {
    "nama": "Pablo12",
    "jenis_customer": "Personal",
    "nomor_identitas": "123123123",
    "nomor_telepon": "081233214432",
    "email": "abc@gmail.com",
    "alamat": "Jl. Jalan"
  }
}

###
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "akun": {
    "username": "karyawan3",
    "password": "rahasia",
    "id_role": 1003
  }
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "customer",
  "password" : "rahasia"
}

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjk4NDc3ODkzLCJleHAiOjE2OTg5OTYyOTN9.Y1PHfvHXM1U7hl6qUYAwRyoQ0aKKvDn3iOnqnqHSa5k
###

GET http://localhost:3000/api/customer/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjk4NDc4NDEyLCJleHAiOjE2OTg5OTY4MTJ9.cR9ZJVEOd2I1V5Agbd-5qq4y4ehLEea5VkMq8y7v0tk
###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "name" : "Eko Kurniawan Khannedy"
}

###
PUT http://localhost:3000/api/users/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

{
  "oldPassword" : "rahasia123",
  "newPassword" : "rahasia"
}

###

POST http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nama": "Pablo",
  "jenis_customer": "Group",
  "nomor_identitas": "123123123",
  "nomor_telepon": "081233214432",
  "email": "abc@gmail.com",
  "alamat": "Jl. Jalan"
}

###
PUT http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "akun": {
    "username" : "pablo1233",
    "oldPassword" : "rahasia",
    "newPassword" : "rahasia"
  },
  "customer": {
    "nama": "Pablo12312312231",
    "jenis_customer": "Personal",
    "nomor_identitas": "123123123",
    "nomor_telepon": "081233214432",
    "email": "abc@gmail.com",                                                               
    "alamat": "Jl. Jalan"
  },
  "id_customer" : 7
}

###
POST http://localhost:3000/api/kamar
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzcyMzIwOCwiZXhwIjoxNjk4MjQxNjA4fQ.YerVoVpgAnmRYlN8YBNsMNGo6OOIk0vIYhqcKOfA2Sg

{
  "nomor_kamar": 123425,
  "id_jenis_kamar": 1
}

###
GET http://localhost:3000/api/kamar/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0
###
PUT http://localhost:3000/api/kamar/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

###

PUT http://localhost:3000/api/kamar/23
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nomor_kamar" : 1234,
  "id_jenis_kamar" : 1
}
###
GET http://localhost:3000/api/kamar?nomor_kamar=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0


###


###
POST http://localhost:3000/api/season
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

{
  "nama_season": "Liburan Natal 2021",
  "tanggal_mulai": "2021-12-01",
  "tanggal_selesai": "2021-12-31"
}

###
GET http://localhost:3000/api/season
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

###
PUT http://localhost:3000/api/season/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

{
  "nama_season": "Liburan Natal 2021",
  "tanggal_mulai": "2021-12-01",
  "tanggal_selesai": "2021-12-31"
}

###

PUT http://localhost:3000/api/kamar/23
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nomor_kamar" : 1234,
  "id_jenis_kamar" : 1
}
###
GET http://localhost:3000/api/season?size=50
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 0993d07e-a757-45c6-9c0c-c956076bc709


### Remove Season

DELETE http://localhost:3000/api/season/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0
### Remove Season

DELETE http://localhost:3000/api/kamar/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

### Jenis Kamar 
GET http://localhost:3000/api/jenis-kamar?jenis_kamar=superior
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

### Jenis Kamar by ID
GET http://localhost:3000/api/jenis-kamar/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

### POST Jenis Kamar

POST http://localhost:3000/api/jenis-kamar
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

{
  "jenis_kamar": "Test Jenis Kamar",
  "jenis_bed": "Test Jenis Bed",
  "kapasitas": 2,
  "jumlah_kasur": 123

}


### Jenis Kamar 
GET http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q



### Tarif
GET http://localhost:3000/api/tarif/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q
### Tarif
GET http://localhost:3000/api/customer/2/booking-history
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjk4NDk4MTU0LCJleHAiOjE2OTkwMTY1NTR9.WX5W6a5Gaz_7YXIrfK5YmDOA1uVek4vqGK7Y2vxvNi4


on: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q
### Tarif
GET http://localhost:3000/api/customer/booking/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjk4NDk4MTU0LCJleHAiOjE2OTkwMTY1NTR9.WX5W6a5Gaz_7YXIrfK5YmDOA1uVek4vqGK7Y2vxvNi4