POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "pablo1",
  "password" : "rahasia",
  "name" : "pab krs",
  "roleId" :  1001
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "pablo1",
  "password" : "rahasia"
}

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5NDY3Mjg0NCwiZXhwIjoxNjk1MTkxMjQ0fQ.B43GNc53gJgWUgPu6b44giDE_4BxQas5PyQrdc789LI


###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "name" : "Eko Kurniawan Khannedy"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 0993d07e-a757-45c6-9c0c-c956076bc709

###

POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "first_name" : "ngabdi",
  "last_name" : "ngabdi",
  "email" : "isogaming2@pzn.com",
  "phone" : "324234234234"
}

###

GET http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

###

GET http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

### Update

PUT http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "first_name": "Rully",
  "last_name": "Nugraha",
  "email": "rully@pzn.com",
  "phone": "324234234234"
}

### Delete Contact

DELETE http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

### Create Address

POST http://localhost:3000/api/contacts/316/addresses
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "street" : "Kantor",
  "city" : "Jakarta",
  "province" : "DKI JAKARTA",
  "country" : "Indonesia",
  "postal_code" : "324234"
}


### List Addresses

GET http://localhost:3000/api/contacts/316/addresses
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8


### Get Address

GET http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

### Update Address

PUT http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "street" : "Kantor Bekerja",
  "city" : "Bekasi",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "324234"
}

### Remove Address

DELETE http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8