POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "akun": {
    "username": "pablo323",
    "password": "rahasiaqwe",
    "id_role": 2001
  },
  "customer": {
    "nama": "Pablo1222",
    "jenis_customer": "Personal",
    "nomor_identitas": "123123123",
    "nomor_telepon": "081233214432",
    "email": "abc@gmail.com",
    "alamat": "Jl. Jalan"
  }
}

###
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "akun": {
    "username": "karyawan3",
    "password": "rahasia",
    "id_role": 1003
  }
}

###

POST http://20.2.72.17/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "customer2",
  "password" : "rahasia"
}

###

GET http://localhost:8080/api
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyMiIsImlhdCI6MTY5ODY1NTIwNCwiZXhwIjoxNzAxMjQ3MjA0fQ.ejkVfII83RTyspKYO8wHYJyEA-f8xefzEjiuHO7-qUo
###

GET http://localhost:3000/api/customer/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyMiIsImlhdCI6MTY5ODY1NTIwNCwiZXhwIjoxNzAxMjQ3MjA0fQ.ejkVfII83RTyspKYO8wHYJyEA-f8xefzEjiuHO7-qUo
###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 555ead79-fe4c-4441-9afd-6bf14c3f94f8

{
  "name" : "Eko Kurniawan Khannedy"
}

###
PUT http://localhost:3000/api/users/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyMiIsImlhdCI6MTY5ODY1NTIwNCwiZXhwIjoxNzAxMjQ3MjA0fQ.ejkVfII83RTyspKYO8wHYJyEA-f8xefzEjiuHO7-qUo

{
  "oldPassword" : "rahasia2",
  "newPassword" : "rahasia"
}

###

POST http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nama": "Pablo",
  "jenis_customer": "Group",
  "nomor_identitas": "123123123",
  "nomor_telepon": "081233214432",
  "email": "abc@gmail.com",
  "alamat": "Jl. Jalan"
}

###
PUT http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjk4NjQyNTQ4LCJleHAiOjE2OTkxNjA5NDh9.yuhGmNrwj7s9ZOAmhLu-3nOc_Q3DEtrrHvoFdKGSksg

{
  "customer": {
    "nama": "PabloEdited",
    "jenis_customer": "Personal",
    "nomor_identitas": "123123123",
    "nomor_telepon": "081233214432",
    "email": "abc@gmail.com",                                                               
    "alamat": "Jl. Jalan"
  },
  "id_customer" : 7
}

###
POST http://localhost:3000/api/kamar
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzcyMzIwOCwiZXhwIjoxNjk4MjQxNjA4fQ.YerVoVpgAnmRYlN8YBNsMNGo6OOIk0vIYhqcKOfA2Sg

{
  "nomor_kamar": 123425,
  "id_jenis_kamar": 1
}

###
GET http://localhost:3000/api/kamar/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0
###
PUT http://localhost:3000/api/kamar/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

###

PUT http://localhost:3000/api/kamar/23
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nomor_kamar" : 1234,
  "id_jenis_kamar" : 1
}
###
GET http://localhost:3000/api/kamar?nomor_kamar=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0


###


###
POST http://localhost:3000/api/season
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

{
  "nama_season": "Liburan Natal 2021",
  "tanggal_mulai": "2021-12-01",
  "tanggal_selesai": "2021-12-31"
}

###
GET http://localhost:3000/api/season
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

###
PUT http://localhost:3000/api/season/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

{
  "nama_season": "Liburan Natal 2021",
  "tanggal_mulai": "2021-12-01",
  "tanggal_selesai": "2021-12-31"
}

###

PUT http://localhost:3000/api/kamar/23
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5NzM4NjgxNiwiZXhwIjoxNjk3OTA1MjE2fQ.1KXr2fb-EVNHbLA42zzqqxYpYgNSwhkUQaNjYihN4G0

{
  "nomor_kamar" : 1234,
  "id_jenis_kamar" : 1
}
###
GET http://localhost:3000/api/season?size=50
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 0993d07e-a757-45c6-9c0c-c956076bc709


### Remove Season

DELETE http://localhost:3000/api/season/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0
### Remove Season

DELETE http://localhost:3000/api/kamar/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMTIzMyIsImlhdCI6MTY5Nzk1MjM5MCwiZXhwIjoxNjk4NDcwNzkwfQ.XvBjQyowOZUYmGTqExM-ATtHcnOyJs-QPrMFsH_TMT0

### Jenis Kamar 
GET http://localhost:3000/api/jenis-kamar?jenis_kamar=superior
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

### Jenis Kamar by ID
GET http://localhost:3000/api/jenis-kamar
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

### POST Jenis Kamar

POST http://localhost:3000/api/jenis-kamar
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q

{
  "jenis_kamar": "Test Jenis Kamar",
  "jenis_bed": "Test Jenis Bed",
  "kapasitas": 2,
  "jumlah_kasur": 123

}


### Jenis Kamar 
GET http://localhost:3000/api/customer
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q



### Tarif
GET http://localhost:3000/api/tarif/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvMSIsImlhdCI6MTY5ODEzOTc1OSwiZXhwIjoxNjk4NjU4MTU5fQ.NpI6FQsfvpWVogUDovO1gio0vYuaJjnPDc8H_-2Zo5Q
### Tarif
GET http://localhost:3000/api/customer/3/booking-history?search_params=401
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyMiIsImlhdCI6MTY5ODY1NTIwNCwiZXhwIjoxNzAxMjQ3MjA0fQ.ejkVfII83RTyspKYO8wHYJyEA-f8xefzEjiuHO7-qUo

### Tarif
GET http://localhost:3000/api/customer/booking/P231114-231
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyMiIsImlhdCI6MTY5ODY1NTIwNCwiZXhwIjoxNzAxMjQ3MjA0fQ.ejkVfII83RTyspKYO8wHYJyEA-f8xefzEjiuHO7-qUo


### Tarif
GET http://localhost:3000/api/booking/kamar?tanggal_check_in=2023-11-22&tanggal_check_out=2023-11-24&kamar_attribute=superior
Content-Type: application/json
Accept: application/json

### Fasilitas
GET http://localhost:3000/api/customer/group?size=100
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

### Fasilitas
POST http://localhost:3000/api/booking
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
   "booking" : {
     "id_customer": 2,
      "tanggal_booking": "2023-09-19",
      "tanggal_check_in": "2023-11-22 08:00:00",
      "tanggal_check_out": "2023-11-24 10:00:00",
      "tamu_dewasa": 2,
      "tamu_anak": 8,
      "tanggal_pembayaran": "2023-09-20",
      "jenis_booking": "Personal",
      "status_booking": "Booked"
   },
   "detail_booking" : [
    {
      "id_jenis_kamar": 1,
      "jumlah": 2,
      "sub_total": 480000
    }
    
   ],
   "fasilitas" : [
    {
      "id_fasilitas": 1,
      "jumlah": 2,
      "sub_total": 480000
    }
   ]
}

### Fasilitas
GET http://localhost:3000/api/jenis-kamar/status?id_jenis_kamar=1&tanggal_check_in=2023-11-22 08:00:00&tanggal_check_out=2023-11-24 10:00:00
Content-Type: application/json
Accept: application/json

### Fasilitas

### Fasilitas
PUT http://localhost:3000/api/booking/change-status/P231114-451
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
   "status_booking" : "coba"
}

### Fasilitas

### Fasilitas
GET http://localhost:3000/api/customer/booking/P231114-451
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs


### Fasilitas
PUT http://localhost:3000/api/booking/cancel/P231122-95
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs


### Fasilitas
GET http://localhost:3000/api/booking/check-in/search
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

### Fasilitas
PUT http://localhost:3000/api/booking/no-rekening/P231117-894
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
    "status_booking" : "coba",
    "no_rekening" : "12341234"
}

### Fasilitas
PUT http://localhost:3000/api/booking/fasilitas/G231120-453
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
    "fasilitas" : [
        {
            "id_fasilitas" : 1,
            "jumlah" : 4,
            "sub_total" : 480000
        },
        {
            "id_fasilitas" : 2,
            "jumlah" : 4,
            "sub_total" : 480000
        }
    ]
}

### Fasilitas
POST http://localhost:3000/api/invoice
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
    "invoice" :{
      "id_booking" : "P231122-748",
      "id_pegawai_fo" : 3
    },
    "fasilitas" : [
        {
            "id_fasilitas" : 1,
            "jumlah" : 4,
            "sub_total" : 480000
        },
        {
            "id_fasilitas" : 2,
            "jumlah" : 4,
            "sub_total" : 480000
        }
    ]
}

### Fasilitas
POST http://localhost:3000/api/laporan/jumlah-tamu
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
    "tahun" : 2023,
    "bulan" : 11
}

### Fasilitas
POST http://localhost:3000/api/laporan/pendapatan-bulanan
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtIiwiaWF0IjoxNjk4NzU0ODU5LCJleHAiOjE3MDEzNDY4NTl9.46MklXr0lciK4Y7bNaJIBrURDmZHDUrCaYB0oBZfyfs

{
    "tahun" : 2023
}


